A=list.files(pattern="junction.count.txt")
j=length(A)
i=1
intr=read.table("constutive.intron.name",head=F)
colnames(intr)=c("intron")
while(i<=j){
data<-read.table(A[i],head=F)
colnames(data)=c("intron","count")
data=merge(intr,data)
nm=paste(substr(A[i],1,nchar(A[i])-18),"exon-exon.txt",sep="")
write.table(data,nm,row.names=F)
i=i+1}
