require(dplyr)
A<-list.files(pattern="exon-exon.txt")
B<-list.files(pattern="exon_intron.count.txt")
i=1
j=length(A)
while(i<=j){
ee<-read.table(A[i],head=T)
ei<-read.table(B[i],head=F)
colnames(ei)<-c("intron","EI")
intron<-data.frame(intron=union(ee$intron,ei$intron))
ee1<-merge(intron,ee)
ee1<-select(ee1,intron,count) %>% rename(EE=count)
ee2<-data.frame(intron=setdiff(intron$intron,ee1$intron))
ee2$EE=0
ee<-rbind(ee1,ee2)
ei1<-merge(intron,ei)
ei2<-data.frame(intron=setdiff(intron$intron,ei1$intron))
ei2$EI=0
ei<-rbind(ei1,ei2)
ee_ei<-merge(ee,ei)
ee_ei<-ee_ei[which(rowSums(ee_ei[,2:3])>=5),]
nm=paste(substr(A[i],1,nchar(A[i])-14),"_EE_EI.txt",sep="")
write.csv(ee_ei,nm,row.names=F)
i=i+1}
